[package]
name = "shim-api"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
# IPC
interprocess.workspace = true