name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: "always"

jobs:
  importer:
    strategy:
      matrix:
        profile:
          - type: "dev"
            dir: "debug"
        target:
          - runner: "windows-2025"
            ext: ".exe"
          - runner: "macos-13"
            ext: ""

    runs-on: ${{ matrix.target.runner }}

    steps:
    - uses: "actions/checkout@v4"

    - name: "Cache"
      uses: "actions/cache@v4"
      with:
        path: |
          "~/.cargo/registry"
          "~/.cargo/git"
          "target"
        key: "${{ runner.os }}-${{ matrix.profile.type }}-cargo-${{ hashFiles('Cargo.lock') }}"
  
    - name: "Build"
      run: "cargo build --profile ${{ matrix.profile.type }} --verbose"

    - name: "Run tests"
      run: "cargo test --profile ${{ matrix.profile.type }} --verbose"

    - name: "Upload artifacts"
      uses: "actions/upload-artifact@v4"
      with:
        name: "Importer-${{ matrix.target.runner }}-${{ matrix.profile.type }}"
        path: "target/${{ matrix.profile.dir }}/*${{ matrix.target.ext }}"
        if-no-files-found: "error"

  plugin:
    strategy:
      matrix:
        profile:
          - type: "dev"

    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: "./plugin"

    steps:
    - uses: "actions/checkout@v4"

    - name: "Setup Node"
      uses: "actions/setup-node@v4"
      with:
        node-version: 24
        cache-dependency-path: "plugin/package-lock.json"
        cache: "npm"
  
    - name: "Install dependencies"
      run: "npm ci"

    - name: "Build"
      run: "npm run build:${{ matrix.profile.type }}"

    - name: "Run tests"
      run: "npm test"

    - name: "Upload artifacts"
      uses: "actions/upload-artifact@v4"
      with:
        name: "Plugin"
        path: "plugin/dist/zo_importer.xpi"
        if-no-files-found: "error"